GET http://127.0.0.1:8080/health HTTP/1.1
content-type: application/json

###
GET http://127.0.0.1:8080/api/v1/plugins HTTP/1.1
content-type: application/json

###
POST http://127.0.0.1:8080/api/v1/plugins/plugin_a/execute HTTP/1.1
content-type: application/json

{
    "input": "{\"operation\": \"uppercase\", \"text\": \"hello\"}"
}

###
POST http://127.0.0.1:8080/api/v1/plugins/plugin_b/execute HTTP/1.1
content-type: application/json

{
    "input": "{\"operation\": \"sqrt\", \"numbers\": [16]}"
}

###
POST http://127.0.0.1:8080/api/v1/plugins/plugin_c/execute HTTP/1.1
content-type: application/json

{
    "input": "{\"operation\": \"query\", \"data\": \"{\\\"user\\\":{\\\"name\\\":\\\"John\\\",\\\"age\\\":30}}\", \"path\": \"user.name\"}"
}

###
PUT http://127.0.0.1:8080/api/v1/plugins/plugin_a/enable HTTP/1.1
content-type: application/json
