[package]
name = "dyn-plug-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
libloading = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
log = "0.4"

[dev-dependencies]
tempfile = "3.8"
env_logger = "0.10"